pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
              echo "${emailRecipient}"
            }
        }
        stage('Build') {
            steps {
                echo "${github_repo}"
            }
        }
    }
}
